### ISSUE TITLE
flippedform.com is down

### ISSUE THREAD

**Issue by daisylb** [kemitchell/flippedform.com#2]
I love this site, and it's a very useful and concise explanation to be able to reference when discussing software licenses and whether they necessarily need to be as wordy as they often are, but I've just noticed today that attempting to connect to `flippedform.com` results in the connection being dropped.

**Comment by kemitchell** [comment]
Thanks for reporting, @daisylb. Apparently something went awry with my server network configuration, causing IPv4 requests to get served and IPv6 requests to go nowhere. I think I've fixed it now.
